<?php
/** Deterministic no-cost functional coverage for 1.4.1 Clear Chat. */

class ACL_AR_ClearFakeSwitchboard implements \ACL\AgentRooms\Contracts\SwitchboardClientInterface {
	public int $calls = 0;
	public array $requests = array();
	public $during_send = null;
	public bool $brain = false;
	public function send( array $request ) {
		$this->calls++; $this->requests[] = $request;
		if ( is_callable( $this->during_send ) ) { ( $this->during_send )(); $this->during_send = null; }
		if ( $this->brain ) {
			$rows=array();foreach((array)($request['metadata']['agent_ids']??array())as$id){$rows[]=array('agent_id'=>(int)$id,'content'=>'POST CLEAR BRAIN '.(int)$id);}
			return array('content'=>wp_json_encode(array('responses'=>$rows)),'usage'=>array('prompt_tokens'=>11,'completion_tokens'=>7,'total_tokens'=>18),'estimated_cost'=>0);
		}
		return array('content'=>'POST CLEAR INDEPENDENT','usage'=>array('prompt_tokens'=>9,'completion_tokens'=>4,'total_tokens'=>13),'estimated_cost'=>0);
	}
}

class ACL_AR_ClearRecoveryMessageRepository extends \ACL\AgentRooms\Repositories\MessageRepository {
	public $after_find = null;
	public function find_by_response_job_id( int $job_id ): ?array {
		$response = parent::find_by_response_job_id( $job_id );
		if ( $response && is_callable( $this->after_find ) ) {
			$callback         = $this->after_find;
			$this->after_find = null;
			$callback( $response );
		}
		return $response;
	}
}

class ACL_AR_ClearChatTest extends ACL_AR_TestCase {
	private int $owner=0,$member=0,$room=0,$disabled_room=0,$agent=0,$brain_agent=0,$brain=0;
	private string $prefix='';
	private \ACL\AgentRooms\Repositories\RoomRepository $rooms;
	private \ACL\AgentRooms\Repositories\MessageRepository $messages;
	private \ACL\AgentRooms\Repositories\EventRepository $events;
	private \ACL\AgentRooms\Services\RoomEventService $writer;
	private $clear_health_before = null;

	public function run():void{
		$this->prefix='clear-120-'.gmdate('YmdHis').'-'.wp_generate_password(5,false,false);
		$this->clear_health_before=get_option('acl_ar_clear_health',null);
		add_filter('acl_ar_brain_provider_model_valid',array($this,'allow_fake'),10,3);
		$this->owner=(int)wp_insert_user(array('user_login'=>$this->prefix.'-owner','user_pass'=>wp_generate_password(20),'user_email'=>$this->prefix.'-owner@example.test','role'=>'administrator'));
		$this->member=(int)wp_insert_user(array('user_login'=>$this->prefix.'-member','user_pass'=>wp_generate_password(20),'user_email'=>$this->prefix.'-member@example.test','role'=>'subscriber'));
		get_user_by('id',$this->member)->add_cap('acl_ar_use_rooms');
		$this->assert_true($this->owner>0&&$this->member>0,'Clear Chat users were not created.');
		wp_set_current_user($this->owner);$this->rooms=new \ACL\AgentRooms\Repositories\RoomRepository();$this->messages=new \ACL\AgentRooms\Repositories\MessageRepository();$this->events=new \ACL\AgentRooms\Repositories\EventRepository();$this->writer=new \ACL\AgentRooms\Services\RoomEventService($this->events);
		try{$this->schema_and_settings();$this->clear_contract();$this->query_contracts();$this->runtime_races();$this->rest_health_and_source();}finally{$this->cleanup();remove_filter('acl_ar_brain_provider_model_valid',array($this,'allow_fake'),10);wp_set_current_user(0);}
	}
	public function allow_fake($allowed,string $provider,string $model):?bool{return 'controlled-fake'===$provider?true:$allowed;}

	private function schema_and_settings():void{
		global$wpdb;$this->assert_same('1.5.6',ACL_AR_VERSION,'Plugin version.');$this->assert_same('1.4.1',ACL_AR_DB_VERSION,'DB version.');\ACL\AgentRooms\Installer::install();$before=$this->fingerprint();\ACL\AgentRooms\Installer::install();$this->assert_same($before,$this->fingerprint(),'Installer twice changed schema.');$this->assert_same('1.4.1',(string)get_option('acl_ar_db_version'),'Installed version.');
		$columns=$wpdb->get_results($wpdb->prepare('SELECT COLUMN_NAME,COLUMN_TYPE,IS_NULLABLE,COLUMN_DEFAULT FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=%s AND TABLE_NAME=%s',DB_NAME,$wpdb->prefix.'acl_ar_rooms'),ARRAY_A);$map=array_column($columns,null,'COLUMN_NAME');
		foreach(array('allow_chat_clear','cleared_through_event_id','chat_cleared_at','chat_cleared_by_user_id')as$c){$this->assert_true(isset($map[$c]),'Missing room column '.$c);}
		$this->assert_same('0',(string)$map['allow_chat_clear']['COLUMN_DEFAULT'],'Clear default is not disabled.');$this->assert_same('NO',$map['allow_chat_clear']['IS_NULLABLE'],'Clear flag is nullable.');$this->assert_same('YES',$map['cleared_through_event_id']['IS_NULLABLE'],'Cutoff is not nullable.');
		$indexes=$wpdb->get_col($wpdb->prepare('SELECT DISTINCT INDEX_NAME FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=%s AND TABLE_NAME=%s',DB_NAME,$wpdb->prefix.'acl_ar_rooms'));sort($indexes);$expected_indexes=array('PRIMARY','owner_user_id','slug','type','visibility');sort($expected_indexes);$this->assert_same($expected_indexes,$indexes,'Unapproved room index added.');
		$base=array('owner_user_id'=>$this->owner,'title'=>$this->prefix.' Disabled','slug'=>$this->prefix.'-disabled','type'=>'private','visibility'=>'private','status'=>'active','agent_reply_mode'=>'manual','max_context_messages'=>20,'max_agents_per_turn'=>3);
		$this->disabled_room=(int)$this->rooms->create($base);$this->assert_true($this->disabled_room>0,'Disabled room create failed.');$this->assert_same(false,$this->rooms->find($this->disabled_room)['allow_chat_clear'],'New room did not default disabled.');
		$base['title']=$this->prefix.' Enabled';$base['slug']=$this->prefix.'-enabled';$this->room=(int)$this->rooms->create($base);$this->assert_same(false,$this->rooms->find($this->room)['allow_chat_clear'],'Second new room did not default disabled.');$enabled=$this->rooms->find($this->room);$enabled['allow_chat_clear']=true;$this->assert_same(true,$this->rooms->update($this->room,$enabled),'Enabling clear failed.');$this->assert_same(true,$this->rooms->find($this->room)['allow_chat_clear'],'Enabled setting was not saved.');$enabled=$this->rooms->find($this->room);$enabled['allow_chat_clear']=false;$this->rooms->update($this->room,$enabled);$this->assert_same(false,$this->rooms->find($this->room)['allow_chat_clear'],'Disabled setting was not saved.');$enabled['allow_chat_clear']=true;$this->rooms->update($this->room,$enabled);
		$this->rooms->add_member($this->room,$this->member,'member');$this->assert_same(true,$this->rooms->is_member($this->room,$this->member),'Member assignment failed.');
		$agents=new \ACL\AgentRooms\Repositories\AgentRepository();$this->agent=(int)$agents->create(array('owner_user_id'=>$this->owner,'name'=>$this->prefix.' Independent','slug'=>$this->prefix.'-independent','description'=>'Independent clear test','provider_route'=>'controlled-fake','model'=>'independent-model','system_prompt'=>'INDEPENDENT PERSONA','visibility'=>'private','enabled'=>1,'execution_mode'=>'independent'));
		$brains=new \ACL\AgentRooms\Repositories\BrainRepository();$this->brain=(int)$brains->create(array('owner_user_id'=>$this->owner,'name'=>$this->prefix.' Brain','slug'=>$this->prefix.'-brain','provider'=>'controlled-fake','model'=>'brain-model','orchestration_prompt'=>'BRAIN CLEAR TEST','max_tokens_per_agent'=>200,'max_total_tokens'=>600,'enabled'=>1));
		$this->brain_agent=(int)$agents->create(array('owner_user_id'=>$this->owner,'name'=>$this->prefix.' Brain Agent','slug'=>$this->prefix.'-brain-agent','description'=>'Brain clear test','provider_route'=>'unused-provider','model'=>'unused-model','system_prompt'=>'BRAIN PERSONA','visibility'=>'private','enabled'=>1,'execution_mode'=>'brain','brain_id'=>$this->brain));$this->assert_true($this->agent>0&&$this->brain>0&&$this->brain_agent>0,'Runtime fixtures failed.');$this->assert_same(true,$this->rooms->assign_agents($this->room,array($this->agent,$this->brain_agent)),'Agent assignment failed.');
	}

	private function clear_contract():void{
		global$wpdb;$service=new \ACL\AgentRooms\Services\RoomClearService($this->rooms,$this->events);$this->assert_wp_error($service->clear($this->disabled_room,$this->owner,$this->prefix.'-disabled-key'),'Disabled room allowed clear.');$this->assert_wp_error($service->clear($this->room,$this->member,$this->prefix.'-member-key-0001'),'Member allowed clear.');
		$old_message=$this->legacy('OLD SECRET HUMAN',$this->owner);$old_action=$this->writer->create(array('room_id'=>$this->room,'event_type'=>'action','actor_type'=>'user','actor_id'=>$this->owner,'audience_type'=>'room','content'=>'OLD SECRET ACTION'));$old_dice=$this->writer->create(array('room_id'=>$this->room,'event_type'=>'dice_roll','actor_type'=>'user','actor_id'=>$this->owner,'audience_type'=>'room','metadata'=>array('notation'=>'d20','rolls'=>array(7),'total'=>7)));$this->assert_true(is_array($old_message)&&is_array($old_action)&&is_array($old_dice),'Pre-clear transcript fixtures failed.');
		$jobs=new \ACL\AgentRooms\Repositories\JobRepository();$job_id=(int)$jobs->create($this->room,(int)$old_message['legacy_message_id'],$this->agent,\ACL\AgentRooms\Repositories\JobRepository::request_key('clear-pending',$this->room,(int)$old_message['legacy_message_id'],$this->agent));$runs=new \ACL\AgentRooms\Repositories\BrainRunRepository();$run=$runs->create($this->room,$this->brain,(int)$old_message['id'],array($this->brain_agent),'controlled-fake','brain-model');$this->assert_same('pending',$jobs->find($job_id)['status'],'Pending job fixture failed.');$this->assert_same('pending',$run['status'],'Pending Brain run fixture failed.');
		$before=array('events'=>(int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM {$wpdb->prefix}acl_ar_events WHERE room_id=%d",$this->room)),'messages'=>(int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM {$wpdb->prefix}acl_ar_messages WHERE room_id=%d",$this->room)),'jobs'=>(int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM {$wpdb->prefix}acl_ar_agent_jobs WHERE room_id=%d",$this->room)),'runs'=>(int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM {$wpdb->prefix}acl_ar_brain_runs WHERE room_id=%d",$this->room)),'search'=>(int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM {$wpdb->prefix}acl_ar_event_search WHERE room_id=%d",$this->room)));
		$max_before=$this->events->highest_id($this->room);$result=$service->clear($this->room,$this->owner,$this->prefix.'-clear-key-0001');$this->assert_true(is_array($result)&&$result['cleared'],'Manager clear failed.');$this->assert_same($max_before,$result['cleared_through_event_id'],'Clear did not store highest event ID.');$room=$this->rooms->find($this->room);$this->assert_same($max_before,(int)$room['cleared_through_event_id'],'Room cutoff mismatch.');$this->assert_same($this->owner,(int)$room['chat_cleared_by_user_id'],'Clear actor mismatch.');$this->assert_true(''!==(string)$room['chat_cleared_at'],'Clear timestamp missing.');$event=$this->events->find((int)$result['clear_event_id']);$this->assert_same('room_clear',$event['event_type'],'Clear event type.');$this->assert_same('user',$event['actor_type'],'Clear actor type.');$this->assert_same($this->owner,(int)$event['actor_id'],'Clear actor id.');$this->assert_same('room',$event['target_type'],'Clear target type.');$this->assert_same($this->room,(int)$event['target_id'],'Clear target id.');$this->assert_same('room',$event['audience_type'],'Clear audience.');$this->assert_same('',$event['content'],'Clear event exposed content.');$this->assert_same($max_before,(int)$event['metadata']['cleared_through_event_id'],'Clear metadata cutoff.');$this->assert_same('canceled',$jobs->find($job_id)['status'],'Pending independent job not canceled.');$this->assert_same('canceled',$runs->find((int)$run['id'])['status'],'Pending Brain run not canceled.');
		$this->assert_same($before['events']+1,(int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM {$wpdb->prefix}acl_ar_events WHERE room_id=%d",$this->room)),'Clear deleted or duplicated events.');$this->assert_same($before['messages'],(int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM {$wpdb->prefix}acl_ar_messages WHERE room_id=%d",$this->room)),'Clear deleted messages.');$this->assert_same($before['jobs'],(int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM {$wpdb->prefix}acl_ar_agent_jobs WHERE room_id=%d",$this->room)),'Clear deleted jobs.');$this->assert_same($before['runs'],(int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM {$wpdb->prefix}acl_ar_brain_runs WHERE room_id=%d",$this->room)),'Clear deleted Brain runs.');$this->assert_same($before['search'],(int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM {$wpdb->prefix}acl_ar_event_search WHERE room_id=%d",$this->room)),'Clear deleted search rows.');
		$duplicate=$service->clear($this->room,$this->owner,$this->prefix.'-clear-key-0001');$this->assert_same((int)$result['clear_event_id'],(int)$duplicate['clear_event_id'],'Duplicate key returned another event.');$this->assert_same(true,$duplicate['duplicate'],'Duplicate not identified.');$this->assert_same(1,(int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM {$wpdb->prefix}acl_ar_events WHERE room_id=%d AND event_type='room_clear'",$this->room)),'Duplicate clear event created.');$noop=$service->clear($this->room,$this->owner,$this->prefix.'-clear-key-0002');$this->assert_same(false,$noop['cleared'],'No-new-event clear was not a no-op.');$this->assert_same(0,(int)$noop['clear_event_id'],'No-op emitted an event.');
	}

	private function query_contracts():void{
		$app=new \ACL\AgentRooms\Services\RoomApplicationService($this->rooms,new \ACL\AgentRooms\Services\AccessService($this->rooms));$page=$app->events($this->room,$this->owner,'','',100);$types=array_column($page['events'],'type');$this->assert_same(array('room_clear'),$types,'Initial history crossed cutoff or lost clear event.');$this->assert_same(false,$page['paging']['has_more_before'],'Earlier history crosses cutoff.');$old_cursor=(new \ACL\AgentRooms\Services\EventCursor())->encode($this->room,'before',999999,0);$this->assert_wp_error($app->events($this->room,$this->owner,$old_cursor,'',20),'Stale pre-clear event cursor was accepted.');$this->assert_same((int)$this->rooms->find($this->room)['cleared_through_event_id'],(int)$page['sync']['cleared_through_event_id'],'Sync cutoff missing.');
		$search=new \ACL\AgentRooms\Services\EventSearchService();$found=$search->search($this->room,$this->owner,'OLD SECRET','',20);$this->assert_same(0,count($found['results']),'Search returned cleared content.');$this->assert_wp_error($search->context($this->room,$this->owner,(int)$this->events->highest_transcript_id($this->room),3),'Cleared context target was returned.');$this->assert_same(null,$this->messages->latest_user_message_for_room($this->room),'Latest user message query crossed cutoff.');
		$cleared_id=(int)$this->rooms->find($this->room)['cleared_through_event_id'];$policy=new \ACL\AgentRooms\Services\MessageInteractionPolicy($this->rooms,new \ACL\AgentRooms\Services\AccessService($this->rooms),$this->events);$target=$this->events->scan_room_before($this->room,$cleared_id+1,100);$target_id=0;foreach($target as$e){if('message'===$e['event_type']){$target_id=(int)$e['id'];break;}}$this->assert_true($target_id>0,'Cleared message target missing.');$this->assert_wp_error($policy->target($this->room,$target_id,$this->owner,'reply'),'Reply to cleared event allowed.');$this->assert_wp_error($policy->target($this->room,$target_id,$this->owner,'edit'),'Edit to cleared event allowed.');$this->assert_wp_error($policy->target($this->room,$target_id,$this->owner,'reaction'),'Reaction to cleared event allowed.');$this->assert_wp_error((new \ACL\AgentRooms\Services\ModerationService())->remove_message($this->room,$target_id),'Moderation returned cleared content.');
		$read=(new \ACL\AgentRooms\Services\ReadStateService())->state($this->room,$this->member);$this->assert_same($cleared_id,(int)$read['last_read_event_id'],'Effective read boundary ignored cutoff.');$this->assert_same(0,(int)$read['unread_count'],'Cleared content remained unread.');
		$post_user=$this->legacy('POST CLEAR USER',$this->owner);$post_agent=$this->writer->create(array('room_id'=>$this->room,'event_type'=>'message','actor_type'=>'agent','actor_id'=>$this->agent,'audience_type'=>'room','content'=>'POST CLEAR AGENT'));$this->assert_true((int)$post_user['id']>$cleared_id&&(int)$post_agent['id']>$cleared_id,'Post-clear events are not newer.');$read=(new \ACL\AgentRooms\Services\ReadStateService())->state($this->room,$this->member);$this->assert_same(2,(int)$read['unread_count'],'Post-clear unread behavior is wrong.');$context=(new \ACL\AgentRooms\Services\ContextBuilder())->build($this->rooms->find($this->room),array('id'=>$this->agent));$serialized=wp_json_encode($context);$this->assert_true(false===strpos($serialized,'OLD SECRET'),'Independent context includes cleared content.');$this->assert_true(false!==strpos($serialized,'POST CLEAR USER'),'Independent context lost post-clear content.');$brain=(new \ACL\AgentRooms\Repositories\BrainRepository())->find($this->brain);$agent=(new \ACL\AgentRooms\Repositories\AgentRepository())->find($this->brain_agent);$request=(new \ACL\AgentRooms\Services\BrainPromptBuilder())->build_request($this->rooms->find($this->room),$brain,$post_user,array($agent));$this->assert_true(false===strpos($request['system_prompt'],'OLD SECRET'),'Brain context includes cleared content.');$this->assert_true(false!==strpos($request['system_prompt'],'POST CLEAR'),'Brain context lost post-clear content.');
	}

	private function runtime_races():void{
		global$wpdb;$jobs=new \ACL\AgentRooms\Repositories\JobRepository();$runs=new \ACL\AgentRooms\Repositories\BrainRunRepository();$service=new \ACL\AgentRooms\Services\RoomClearService($this->rooms,$this->events);$agents=new \ACL\AgentRooms\Repositories\AgentRepository();
		$trigger=$this->legacy('ORPHAN RESPONSE CLEAR RACE',$this->owner);$job_id=(int)$jobs->create($this->room,(int)$trigger['legacy_message_id'],$this->agent,\ACL\AgentRooms\Repositories\JobRepository::request_key('orphan-clear-race',$this->room,(int)$trigger['legacy_message_id'],$this->agent));$orphan_id=(int)$this->messages->create(array('room_id'=>$this->room,'sender_type'=>'agent','sender_agent_id'=>$this->agent,'content'=>'HIDDEN ORPHAN RESPONSE','response_job_id'=>$job_id,'provider_route'=>'controlled-fake','model'=>'independent-model','prompt_tokens'=>3,'completion_tokens'=>2,'total_tokens'=>5));$recovery_messages=new ACL_AR_ClearRecoveryMessageRepository();$recovery_messages->after_find=function()use($service){$service->clear($this->room,$this->owner,$this->prefix.'-orphan-recovery-clear');};$recovery_fake=new ACL_AR_ClearFakeSwitchboard();$recovery=(new \ACL\AgentRooms\Services\AgentRuntime($jobs,$this->rooms,$agents,$recovery_messages,null,$recovery_fake))->run_job($job_id);$this->assert_wp_error($recovery,'Cleared orphan response was recovered.');$this->assert_same('acl_ar_trigger_cleared',$recovery->get_error_code(),'Cleared orphan recovery returned the wrong error.');$this->assert_same(0,$recovery_fake->calls,'Orphan response recovery called the provider.');$this->assert_same('canceled',$jobs->find($job_id)['status'],'Orphan clear race rewrote the canceled job.');$this->assert_same(null,$this->events->find_by_legacy_message_id($orphan_id),'Orphan clear race created a post-cutoff message event.');$this->assert_true(!$jobs->complete($job_id,$orphan_id),'Tokenless completion rewrote a canceled job.');$visible_messages=$this->messages->for_room($this->room,100,0);$this->assert_true(!in_array($orphan_id,array_map('intval',array_column($visible_messages,'id')),true),'Eventless orphan response became visible after clear.');
		$trigger=$this->legacy('RACING INDEPENDENT',$this->owner);$job_id=(int)$jobs->create($this->room,(int)$trigger['legacy_message_id'],$this->agent,\ACL\AgentRooms\Repositories\JobRepository::request_key('race',$this->room,(int)$trigger['legacy_message_id'],$this->agent));$independent_usage_before=(int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM {$wpdb->prefix}acl_ar_usage WHERE room_id=%d AND agent_id=%d",$this->room,$this->agent));$fake=new ACL_AR_ClearFakeSwitchboard();$fake->during_send=function()use($service){$service->clear($this->room,$this->owner,$this->prefix.'-race-independent');};$runtime=new \ACL\AgentRooms\Services\AgentRuntime($jobs,$this->rooms,$agents,$this->messages,null,$fake);$this->assert_wp_error($runtime->run_job($job_id),'Cleared running independent result was accepted.');$this->assert_same(1,$fake->calls,'Independent race did not call controlled seam once.');$this->assert_same('canceled',$jobs->find($job_id)['status'],'Running independent job not canceled.');$this->assert_same(0,(int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM {$wpdb->prefix}acl_ar_messages WHERE response_job_id=%d",$job_id)),'Independent response inserted after clear.');$this->assert_same(0,(int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM {$wpdb->prefix}acl_ar_events WHERE job_id=%d AND event_type='message'",$job_id)),'Independent response event inserted after clear.');$this->assert_same($independent_usage_before+1,(int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM {$wpdb->prefix}acl_ar_usage WHERE room_id=%d AND agent_id=%d",$this->room,$this->agent)),'Discarded clear-race response usage was not recorded exactly once.');
		$trigger=$this->legacy('RACING BRAIN',$this->owner);$run=$runs->create($this->room,$this->brain,(int)$trigger['id'],array($this->brain_agent),'controlled-fake','brain-model');$brain_fake=new ACL_AR_ClearFakeSwitchboard();$brain_fake->brain=true;$brain_fake->during_send=function()use($service){$service->clear($this->room,$this->owner,$this->prefix.'-race-brain');};$brain_runtime=new \ACL\AgentRooms\Services\BrainRuntime($runs,null,$this->rooms,$agents,$this->events,$this->messages,null,null,$brain_fake);$this->assert_wp_error($brain_runtime->run((int)$run['id']),'Cleared running Brain result was accepted.');$this->assert_same(1,$brain_fake->calls,'Brain race did not call controlled seam once.');$this->assert_same('canceled',$runs->find((int)$run['id'])['status'],'Running Brain run not canceled.');$this->assert_same(0,(int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM {$wpdb->prefix}acl_ar_messages WHERE brain_run_id=%d",(int)$run['id'])),'Brain response inserted after clear.');$this->assert_same(1,(int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM {$wpdb->prefix}acl_ar_usage WHERE brain_run_id=%d",(int)$run['id'])),'Actual Brain usage was not recorded exactly once.');
		$trigger=$this->legacy('NEW INDEPENDENT',$this->owner);$job_id=(int)$jobs->create($this->room,(int)$trigger['legacy_message_id'],$this->agent,\ACL\AgentRooms\Repositories\JobRepository::request_key('post',$this->room,(int)$trigger['legacy_message_id'],$this->agent));$ok_fake=new ACL_AR_ClearFakeSwitchboard();$ok=(new \ACL\AgentRooms\Services\AgentRuntime($jobs,$this->rooms,$agents,$this->messages,null,$ok_fake))->run_job($job_id);$this->assert_same('completed',$ok['status'],'New post-clear Independent job failed.');$this->assert_same(1,$ok_fake->calls,'New Independent job call count.');$this->assert_same(1,(int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM {$wpdb->prefix}acl_ar_messages WHERE response_job_id=%d",$job_id)),'New Independent response missing.');$response=$this->messages->find_by_response_job_id($job_id);$response_event=$this->events->find_by_legacy_message_id((int)$response['id']);$worker_first_clear=$service->clear($this->room,$this->owner,$this->prefix.'-worker-first-clear');$this->assert_true(is_array($worker_first_clear)&&$worker_first_clear['cleared'],'Worker-first response was not followed by a clear.');$this->assert_true($jobs->cancel($job_id,'chat_cleared'),'Completed Independent cancellation was not idempotent.');$this->assert_same('completed',$jobs->find($job_id)['status'],'Late clear rewrote a completed Independent job.');$this->assert_true((int)$response_event['id']<=(int)$worker_first_clear['cleared_through_event_id'],'Worker-first response event was not covered by the clear cutoff.');$visible=(new \ACL\AgentRooms\Services\RoomApplicationService())->events($this->room,$this->owner,'','',100);$this->assert_true(!in_array((int)$response_event['id'],array_map('intval',array_column($visible['events'],'id')),true),'Clear cutoff exposed the worker-first assistant response.');
		$trigger=$this->legacy('NEW BRAIN',$this->owner);$run=$runs->create($this->room,$this->brain,(int)$trigger['id'],array($this->brain_agent),'controlled-fake','brain-model');$ok_brain=new ACL_AR_ClearFakeSwitchboard();$ok_brain->brain=true;$done=(new \ACL\AgentRooms\Services\BrainRuntime($runs,null,$this->rooms,$agents,$this->events,$this->messages,null,null,$ok_brain))->run((int)$run['id']);$this->assert_same('completed',$done['status'],'New post-clear Brain run failed.');$this->assert_same(1,$ok_brain->calls,'New Brain run call count.');$this->assert_same(1,(int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM {$wpdb->prefix}acl_ar_messages WHERE brain_run_id=%d",(int)$run['id'])),'New Brain response missing.');
	}

	private function rest_health_and_source():void{
		global$wpdb;$controller=new \ACL\AgentRooms\Rest\RoomClearController($this->rooms,new \ACL\AgentRooms\Services\AccessService($this->rooms));add_action('rest_api_init',array($controller,'register_routes'));do_action('rest_api_init');remove_action('rest_api_init',array($controller,'register_routes'));$routes=rest_get_server()->get_routes();$route='/acl-agent-rooms/v1/rooms/(?P<room_id>[\d]+)/clear';$this->assert_true(isset($routes[$route]),'Clear REST route missing.');$methods=$routes[$route][0]['methods'];$this->assert_true('POST'===$methods||(is_array($methods)&&!empty($methods['POST'])),'Clear REST method.');$request=new \WP_REST_Request('POST','/');$request->set_param('room_id',$this->room);$request->set_param('confirm',true);$request->set_param('idempotency_key',$this->prefix.'-rest-key');$this->assert_wp_error($controller->permissions($request),'Missing nonce accepted.');$request->set_header('X-WP-Nonce',wp_create_nonce('wp_rest'));wp_set_current_user($this->member);$this->assert_wp_error($controller->permissions($request),'Ordinary member REST clear accepted.');wp_set_current_user(0);$this->assert_wp_error($controller->permissions($request),'Unauthenticated REST clear accepted.');wp_set_current_user($this->owner);$bad=new \WP_REST_Request('POST','/');$bad->set_param('room_id',$this->room);$bad->set_header('X-WP-Nonce','invalid');$this->assert_wp_error($controller->permissions($bad),'Invalid nonce accepted.');
		$endpoint_source=file_get_contents(dirname(__DIR__).'/includes/Rest/RoomClearController.php');foreach(array("'confirm'","'idempotency_key'",'private, no-store','can_clear_room','verify_nonce')as$n){$this->assert_true(false!==strpos($endpoint_source,$n),'REST contract missing '.$n);}$api=file_get_contents(dirname(__DIR__).'/assets/js/room/api.js');$this->assert_true(false!==strpos($api,"Api.prototype.clearRoom"),'Client clear route missing.');$this->assert_true(false!==strpos($api,"buildRestUrl"),'Central REST URL composer missing.');
		$admin=file_get_contents(dirname(__DIR__).'/includes/Admin/RoomsPage.php');$this->assert_true(false!==strpos($admin,'Enable Clear Chat'),'Admin setting label missing.');$this->assert_true(false!==strpos($admin,'Earlier records remain preserved for audit and retention'),'Admin help text missing.');$shortcode=file_get_contents(dirname(__DIR__).'/includes/Shortcodes/AgentRoomShortcode.php');$this->assert_true(false!==strpos($shortcode,'canClearChat'),'Manager-only bootstrap permission missing.');$clear_js=file_get_contents(dirname(__DIR__).'/assets/js/room/clear-chat.js');$this->assert_true(false===strpos($clear_js,'window.confirm'),'Browser confirm was used.');$this->assert_true(false!==strpos($clear_js,'This will clear the visible transcript for everyone in this room.'),'Confirmation copy missing.');
		$health=(new \ACL\AgentRooms\Services\HealthService())->snapshot();$this->assert_true(isset($health['clear_chat']['invalid_cutoff_references'],$health['clear_chat']['impossible_cutoffs'],$health['clear_chat']['missing_actor_references'],$health['clear_chat']['failed_operations'],$health['clear_chat']['duplicate_retries']),'Clear health checks missing.');$saved=$this->rooms->find($this->disabled_room);$wpdb->update($wpdb->prefix.'acl_ar_rooms',array('cleared_through_event_id'=>PHP_INT_MAX),array('id'=>$this->disabled_room));$broken=(new \ACL\AgentRooms\Services\HealthService())->snapshot();$this->assert_true($broken['clear_chat']['impossible_cutoffs']>=1,'Impossible cutoff not detected.');$wpdb->update($wpdb->prefix.'acl_ar_rooms',array('cleared_through_event_id'=>$saved['cleared_through_event_id']),array('id'=>$this->disabled_room));
		$this->assert_true(false!==strpos(file_get_contents(dirname(__DIR__).'/includes/Services/RoomClearService.php'),'START TRANSACTION'),'Clear transaction missing.');$this->assert_true(false!==strpos(file_get_contents(dirname(__DIR__).'/includes/Repositories/JobRepository.php'),'chat_cleared'),'Independent cancel policy missing.');$this->assert_true(false!==strpos(file_get_contents(dirname(__DIR__).'/includes/Repositories/BrainRunRepository.php'),'chat_cleared'),'Brain cancel policy missing.');$this->assert_true(false!==strpos(file_get_contents(dirname(__DIR__).'/includes/Services/BrainRuntime.php'),'trigger_cleared'),'Brain discard policy missing.');$this->assert_true(false!==strpos(file_get_contents(dirname(__DIR__).'/includes/Services/AgentRuntime.php'),'trigger_cleared'),'Independent discard policy missing.');
	}

	private function legacy(string$content,int$user):array{$id=$this->messages->create(array('room_id'=>$this->room,'sender_type'=>'user','sender_user_id'=>$user,'content'=>$content,'client_request_id'=>$this->prefix.'-'.wp_generate_password(12,false,false)));$event=$this->writer->create_message_event($this->messages->find((int)$id));return $event;}
	private function fingerprint():string{global$wpdb;$like=$wpdb->esc_like($wpdb->prefix.'acl_ar_').'%';$c=$wpdb->get_results($wpdb->prepare('SELECT TABLE_NAME,COLUMN_NAME,ORDINAL_POSITION,COLUMN_TYPE,IS_NULLABLE,COLUMN_DEFAULT,EXTRA FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=%s AND TABLE_NAME LIKE %s ORDER BY TABLE_NAME,ORDINAL_POSITION',DB_NAME,$like),ARRAY_A);$i=$wpdb->get_results($wpdb->prepare('SELECT TABLE_NAME,INDEX_NAME,NON_UNIQUE,SEQ_IN_INDEX,COLUMN_NAME,SUB_PART,INDEX_TYPE FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=%s AND TABLE_NAME LIKE %s ORDER BY TABLE_NAME,INDEX_NAME,SEQ_IN_INDEX',DB_NAME,$like),ARRAY_A);return hash('sha256',wp_json_encode(array($c,$i)));}
	private function cleanup():void{global$wpdb;wp_set_current_user($this->owner);foreach(array($this->room,$this->disabled_room)as$room){if(!$room){continue;}$wpdb->delete($wpdb->prefix.'acl_ar_usage',array('room_id'=>$room),array('%d'));if($this->rooms&&$this->rooms->find($room)){$this->rooms->delete($room);}}$agents=new \ACL\AgentRooms\Repositories\AgentRepository();foreach(array($this->agent,$this->brain_agent)as$id){if($id&&$agents->find($id)){$agents->delete($id);}}if($this->brain){(new \ACL\AgentRooms\Repositories\BrainRepository())->delete($this->brain);}if($this->member){wp_delete_user($this->member);}if($this->owner){wp_delete_user($this->owner);}if(null===$this->clear_health_before){delete_option('acl_ar_clear_health');}else{update_option('acl_ar_clear_health',$this->clear_health_before,false);}}
}
