<?php
use ACL\AgentRooms\Repositories\AgentRepository;
use ACL\AgentRooms\Repositories\RoomRepository;
use ACL\AgentRooms\Services\AccessService;
use ACL\AgentRooms\Shortcodes\AgentRoomShortcode;
class ACL_AR_Phase5UiTest extends ACL_AR_TestCase {
	private RoomRepository $rooms;private AgentRepository $agents;private int $owner=0;private int $outsider=0;private int $room=0;private int $agent=0;private string $prefix='';
	public function run():void{$this->prefix='phase5-'.gmdate('YmdHis').'-'.wp_generate_password(6,false,false);$this->rooms=new RoomRepository();$this->agents=new AgentRepository();$this->set_up();try{$this->test_version_and_schema();$this->pass('phase5_version_and_schema');$this->test_access_and_assets();$this->pass('phase5_access_and_assets');$this->test_safe_bootstrap_and_markup();$this->pass('phase5_safe_bootstrap_and_markup');$this->test_routes();$this->pass('phase5_route_compatibility');}finally{$this->tear_down();}}
	private function set_up():void{$this->owner=$this->user('owner');$this->outsider=$this->user('outsider');wp_set_current_user($this->owner);$this->agent=$this->agents->create(array('name'=>'Classic Agent','slug'=>$this->prefix.'-agent','description'=>'Safe room participant','provider_route'=>'fake','model'=>'fake','system_prompt'=>'never expose me','enabled'=>1));$this->room=$this->rooms->create(array('title'=>'Classic Room','slug'=>$this->prefix,'description'=>'Welcome to the old web','owner_user_id'=>$this->owner,'agent_reply_mode'=>'manual'));$this->rooms->assign_agents($this->room,array($this->agent));}
	private function user(string $suffix):int{$id=wp_insert_user(array('user_login'=>$this->prefix.'-'.$suffix,'user_pass'=>wp_generate_password(20),'user_email'=>$this->prefix.'-'.$suffix.'@example.test','display_name'=>'Phase Five '.ucfirst($suffix),'role'=>'subscriber'));if(is_wp_error($id)){throw new RuntimeException($id->get_error_message());}get_user_by('id',$id)->add_cap('acl_ar_use_rooms');return(int)$id;}
	private function test_version_and_schema():void{global $wpdb;\ACL\AgentRooms\Installer::install();\ACL\AgentRooms\Installer::install();$this->assert_true(version_compare(ACL_AR_VERSION,'1.1.0','>='),'Plugin version regressed.');$this->assert_true(version_compare(ACL_AR_DB_VERSION,'1.1.0','>='),'Database version regressed.');$this->assert_same(ACL_AR_DB_VERSION,(string)get_option('acl_ar_db_version'),'Stored database version did not align.');$expected=array('wp_acl_ar_agent_jobs','wp_acl_ar_agents','wp_acl_ar_brain_runs','wp_acl_ar_brains','wp_acl_ar_conversation_turns','wp_acl_ar_event_reactions','wp_acl_ar_event_search','wp_acl_ar_events','wp_acl_ar_maintenance_runs','wp_acl_ar_messages','wp_acl_ar_room_agents','wp_acl_ar_room_file_versions','wp_acl_ar_room_files','wp_acl_ar_room_members','wp_acl_ar_room_presence','wp_acl_ar_room_presence_sessions','wp_acl_ar_room_reads','wp_acl_ar_room_restrictions','wp_acl_ar_rooms','wp_acl_ar_shared_configs','wp_acl_ar_usage');$actual=$wpdb->get_col("SELECT TABLE_NAME FROM information_schema.TABLES WHERE TABLE_SCHEMA='".esc_sql(DB_NAME)."' AND TABLE_NAME LIKE 'wp_acl_ar_%' ORDER BY TABLE_NAME");$this->assert_same($expected,$actual,'Agent Rooms table set mismatch.');}
	private function test_access_and_assets():void{$shortcode=new AgentRoomShortcode($this->rooms,new AccessService($this->rooms));wp_set_current_user(0);$guest=$shortcode->render(array('id'=>$this->room));$this->assert_true(false!==strpos($guest,'Log in'),'Guest access boundary changed.');wp_set_current_user($this->outsider);$denied=$shortcode->render(array('id'=>$this->room));$this->assert_true(false!==strpos($denied,'do not have access'),'Private room access boundary changed.');wp_dequeue_script('acl-agent-rooms-room');$this->assert_true(!wp_script_is('acl-agent-rooms-room','enqueued'),'Room script was already enqueued outside rendering.');wp_set_current_user($this->owner);$shortcode->render(array('id'=>$this->room));$this->assert_true(wp_script_is('acl-agent-rooms-room','enqueued'),'Room script did not enqueue on rendering.');$this->assert_true(wp_style_is('acl-agent-rooms-room-aol','enqueued'),'AOL room style did not enqueue on rendering.');}
	private function test_safe_bootstrap_and_markup():void{$html=(new AgentRoomShortcode($this->rooms,new AccessService($this->rooms)))->render(array('id'=>$this->room));$this->assert_true(false!==strpos($html,'acl-ar-room-app'),'AOL application mount missing.');foreach(array('acl-ar-room-app__titlebar','acl-ar-room-app__topicbar','acl-ar-room-app__transcript','acl-ar-room-app__members','acl-ar-room-app__toolbar','acl-ar-room-app__composer','acl-ar-room-app__statusbar')as$class){$this->assert_true(false!==strpos($html,$class),'Missing application region '.$class);}$this->assert_true(1===preg_match('/data-bootstrap="([^"]+)"/',$html,$match),'Bootstrap attribute missing.');$data=json_decode(html_entity_decode($match[1],ENT_QUOTES|ENT_HTML5,'UTF-8'),true);$this->assert_same($this->room,(int)$data['roomId'],'Bootstrap room mismatch.');$this->assert_same($this->owner,(int)$data['currentUserId'],'Bootstrap user mismatch.');$this->assert_true(false!==strpos($data['eventEndpoint'],'/events')&&false!==strpos($data['legacyMessageEndpoint'],'/messages'),'Bootstrap endpoints missing.');$encoded=wp_json_encode($data);foreach(array('system_prompt','never expose me','provider_route','api_key','authorization','nonce_value')as$secret){$this->assert_true(false===stripos($encoded,$secret),'Bootstrap exposed '.$secret);}$this->assert_same('Classic Agent',$data['agents'][0]['name'],'Safe agent projection missing.');}
	private function test_routes():void{$routes=rest_get_server()->get_routes();foreach(array('/acl-agent-rooms/v1/rooms/(?P<id>[\d]+)/events','/acl-agent-rooms/v1/rooms/(?P<id>[\d]+)/messages','/acl-agent-rooms/v1/rooms/(?P<id>[\d]+)/agents/(?P<agent_id>[\d]+)/reply')as$route){$this->assert_true(isset($routes[$route]),'Existing REST route missing: '.$route);}}
	private function pass(string $name):void{echo'PASS '.$name.PHP_EOL;}private function tear_down():void{global$wpdb;wp_set_current_user($this->owner);$wpdb->delete($wpdb->prefix.'acl_ar_usage',array('room_id'=>$this->room));if($this->room&&$this->rooms->find($this->room)){$this->rooms->delete($this->room);}if($this->agent){$this->agents->delete($this->agent);}foreach(array($this->owner,$this->outsider)as$user){if($user){wp_delete_user($user);}}wp_set_current_user(0);}
}
