<?php

require_once __DIR__ . '/bootstrap.php';
require_once __DIR__ . '/TestCase.php';
require_once __DIR__ . '/Phase2RegressionTest.php';
require_once __DIR__ . '/Phase3EventTest.php';
require_once __DIR__ . '/Phase4EventApiTest.php';
require_once __DIR__ . '/Phase5UiTest.php';
require_once __DIR__ . '/Phase6InteractionTest.php';
require_once __DIR__ . '/Phase7CommandTest.php';
require_once __DIR__ . '/Phase8PresenceTest.php';
require_once __DIR__ . '/Phase9ProductionTest.php';
require_once __DIR__ . '/Release101RegressionTest.php';
require_once __DIR__ . '/Release102RegressionTest.php';
require_once __DIR__ . '/Release103RegressionTest.php';
require_once __DIR__ . '/SwitchboardCompatibilityTest.php';
require_once __DIR__ . '/SharedBrainOrchestrationTest.php';
require_once __DIR__ . '/ClearChatTest.php';
require_once __DIR__ . '/NaturalConversationTest.php';
require_once __DIR__ . '/Release131SchemaNormalizationTest.php';
require_once __DIR__ . '/Release132SchemaNormalizationTest.php';
require_once __DIR__ . '/RoomProjectFilesTest.php';
require_once __DIR__ . '/MessageResponsivenessTest.php';
require_once dirname( __DIR__, 2 ) . '/acl-agent-rooms-pro/tests/FreeProIntegrationTest.php';

$test = new ACL_AR_Phase2RegressionTest();
try {
	$test->run();
	echo 'PASS phase2_regression assertions=' . $test->assertion_count() . PHP_EOL;
	$phase3 = new ACL_AR_Phase3EventTest();
	$phase3->run();
	echo 'PASS phase3_event_regression assertions=' . $phase3->assertion_count() . PHP_EOL;
	$phase4 = new ACL_AR_Phase4EventApiTest();
	$phase4->run();
	echo 'PASS phase4_event_api assertions=' . $phase4->assertion_count() . PHP_EOL;
	$phase5 = new ACL_AR_Phase5UiTest();
	$phase5->run();
	echo 'PASS phase5_ui assertions=' . $phase5->assertion_count() . PHP_EOL;
	$phase6 = new ACL_AR_Phase6InteractionTest();
	$phase6->run();
	echo 'PASS phase6_interactions assertions=' . $phase6->assertion_count() . PHP_EOL;
	$phase7 = new ACL_AR_Phase7CommandTest();
	$phase7->run();
	echo 'PASS phase7_commands assertions=' . $phase7->assertion_count() . PHP_EOL;
	$phase8 = new ACL_AR_Phase8PresenceTest();
	$phase8->run();
	echo 'PASS phase8_presence assertions=' . $phase8->assertion_count() . PHP_EOL;
	$phase9 = new ACL_AR_Phase9ProductionTest();
	$phase9->run();
	echo 'PASS phase9_release assertions=' . $phase9->assertion_count() . PHP_EOL;
	$release101 = new ACL_AR_Release101RegressionTest();
	$release101->run();
	echo 'PASS release_101_regression assertions=' . $release101->assertion_count() . PHP_EOL;
	$release102 = new ACL_AR_Release102RegressionTest();
	$release102->run();
	echo 'PASS release_102_regression assertions=' . $release102->assertion_count() . PHP_EOL;
	$release103 = new ACL_AR_Release103RegressionTest();
	$release103->run();
	echo 'PASS release_103_regression assertions=' . $release103->assertion_count() . PHP_EOL;
	$switchboard_compatibility = new ACL_AR_SwitchboardCompatibilityTest();
	$switchboard_compatibility->run();
	echo 'PASS switchboard_compatibility assertions=' . $switchboard_compatibility->assertion_count() . PHP_EOL;
	$brain = new ACL_AR_SharedBrainOrchestrationTest();
	$brain->run();
	echo 'PASS shared_brain_orchestration assertions=' . $brain->assertion_count() . PHP_EOL;
	$clear = new ACL_AR_ClearChatTest();
	$clear->run();
	echo 'PASS clear_chat_120 assertions=' . $clear->assertion_count() . PHP_EOL;
	$natural = new ACL_AR_NaturalConversationTest();
	$natural->run();
	echo 'PASS natural_conversation_130 assertions=' . $natural->assertion_count() . PHP_EOL;
	$release131 = new ACL_AR_Release131SchemaNormalizationTest();
	$release131->run();
	echo 'PASS release_131_schema_normalization assertions=' . $release131->assertion_count() . PHP_EOL;
	$release132 = new ACL_AR_Release132SchemaNormalizationTest();
	$release132->run();
	echo 'PASS release_132_schema_normalization assertions=' . $release132->assertion_count() . PHP_EOL;
	$room_files = new ACL_AR_RoomProjectFilesTest();
	$room_files->run();
	echo 'PASS room_project_files_140 assertions=' . $room_files->assertion_count() . PHP_EOL;
	$responsiveness = new ACL_AR_MessageResponsivenessTest();
	$responsiveness->run();
	echo 'PASS message_responsiveness_141 assertions=' . $responsiveness->assertion_count() . PHP_EOL;
	$free_pro = new ACL_AR_FreeProIntegrationTest();
	$free_pro->run();
	echo 'PASS free_pro_integration assertions=' . $free_pro->assertion_count() . PHP_EOL;
	echo 'PASS total_assertions=' . ( $test->assertion_count() + $phase3->assertion_count() + $phase4->assertion_count() + $phase5->assertion_count() + $phase6->assertion_count() + $phase7->assertion_count() + $phase8->assertion_count() + $phase9->assertion_count() + $release101->assertion_count() + $release102->assertion_count() + $release103->assertion_count() + $switchboard_compatibility->assertion_count() + $brain->assertion_count() + $clear->assertion_count() + $natural->assertion_count() + $release131->assertion_count() + $release132->assertion_count() + $room_files->assertion_count() + $responsiveness->assertion_count() + $free_pro->assertion_count() ) . PHP_EOL;
	exit( 0 );
} catch ( Throwable $throwable ) {
	fwrite( STDERR, 'FAIL phase2_regression: ' . $throwable->getMessage() . PHP_EOL );
	exit( 1 );
}
