'use strict';
const fs=require('fs'),path=require('path');
const Transcript=require('../../assets/js/room/transcript.js'),Members=require('../../assets/js/room/member-list.js'),Composer=require('../../assets/js/room/composer.js'),Preferences=require('../../assets/js/room/preferences.js'),Sound=require('../../assets/js/room/sound.js'),App=require('../../assets/js/room/app.js');
let assertions=0;function check(name,value){assertions++;if(!value){throw new Error(name);}console.log('PASS '+name);}
class Classes{constructor(){this.s=new Set();}add(v){this.s.add(v);}remove(v){this.s.delete(v);}toggle(v,on){if(on===undefined){on=!this.s.has(v);}on?this.s.add(v):this.s.delete(v);return on;}contains(v){return this.s.has(v);}}
class Node{constructor(tag){this.tag=tag;this.children=[];this.parentNode=null;this.dataset={};this.attributes={};this.className='';this.classList=new Classes();this.textContent='';this.value='';this.selectionStart=0;this.selectionEnd=0;this.rows=2;this.listeners={};this.style={values:{},setProperty:(k,v)=>{this.style.values[k]=v;}};this.scrollTop=0;this.clientHeight=40;this.hidden=false;this.disabled=false;}get firstChild(){return this.children[0]||null;}get scrollHeight(){return this.children.length*20;}appendChild(n){if(n.tag==='#fragment'){n.children.slice().forEach(c=>this.appendChild(c));return n;}n.parentNode=this;this.children.push(n);return n;}removeChild(n){this.children=this.children.filter(c=>c!==n);}insertBefore(n,b){if(n.tag==='#fragment'){n.children.slice().forEach(c=>this.insertBefore(c,b));return n;}let i=b?this.children.indexOf(b):-1;i<0?this.children.push(n):this.children.splice(i,0,n);n.parentNode=this;return n;}remove(){if(this.parentNode){this.parentNode.removeChild(this);}}setAttribute(k,v){this.attributes[k]=String(v);}getAttribute(k){return this.attributes[k]||null;}addEventListener(k,f){(this.listeners[k]=this.listeners[k]||[]).push(f);}dispatch(k,e){(this.listeners[k]||[]).forEach(f=>f(Object.assign({key:'',preventDefault(){this.prevented=true;}},e||{})));}focus(){this.focused=true;}querySelector(s){if(s==='[type="submit"]'){return this.submitButton||null;}let m=s.match(/^\[data-event-id="(\d+)"\]$/);if(m){return this.children.find(c=>String(c.dataset.eventId)===m[1])||null;}return null;}querySelectorAll(s){if(s==='.acl-ar-message'){return this.children.filter(c=>c.className.indexOf('acl-ar-message')>=0);}return [];}}
class Doc{createElement(t){return new Node(t);}createDocumentFragment(){return new Node('#fragment');}createTextNode(t){let n=new Node('#text');n.textContent=t;return n;}}
function evt(id,type,actor,content){return{id:id,room_id:7,type:type,actor:actor,content:content||'hello',created_at:'2026-07-11T20:00:00+00:00'};}
function run(){const rootDir=path.join(__dirname,'../..'),roomSource=fs.readFileSync(path.join(rootDir,'assets/js/room.js'),'utf8'),appSource=fs.readFileSync(path.join(rootDir,'assets/js/room/app.js'),'utf8'),dialogSource=fs.readFileSync(path.join(rootDir,'assets/js/room/dialogs.js'),'utf8'),template=fs.readFileSync(path.join(rootDir,'templates/room-app.php'),'utf8'),css=fs.readFileSync(path.join(rootDir,'assets/css/room-aol.css'),'utf8');
const workCyclesMatch=roomSource.match(/cycles=0,maxCycles=(\d+)/),maxWorkCycles=workCyclesMatch?parseInt(workCyclesMatch[1],10):0,maxRetryPollMs=5000,independentRetryScheduleMs=(30+120)*1000;
const fakeRoot={listeners:{},classList:new Classes(),addEventListener(k,f){this.listeners[k]=f;},querySelector(){return new Node('div');},dispatchEvent(){}};const prefStub={value:{membersOpen:false},apply(){},toggle(){return true;},set(){}};const config={roomId:7,currentUserId:1,currentUserName:'Me',room:{title:'Room',description:'Topic',visibility:'private',replyMode:'manual',status:'active'},agents:[],permissions:{canManualReply:true}};
check('aol_app_mounts_valid_bootstrap',new App(fakeRoot,config,prefStub,{},{},{},{input:new Node('textarea')}) instanceof App);let invalid=false;try{new App(fakeRoot,{},prefStub,{},{},{},{input:new Node('textarea')});}catch(e){invalid=true;}check('app_rejects_invalid_bootstrap',invalid);
const doc=new Doc(),list=new Node('log'),tr=new Transcript(list,1,doc),human=evt(1,'message',{type:'user',id:2,name:'Other Human'},'<b>safe</b>'),mine=evt(2,'message',{type:'user',id:1,name:'Me'},'mine'),agent=evt(3,'message',{type:'agent',id:9,name:'Bot'},'agent'),system=evt(4,'system_notice',{type:'system',id:null,name:'Room system'},'<script>');
let hn=tr.node(human),mn=tr.node(mine),an=tr.node(agent),sn=tr.node(system);check('flat_transcript_row',hn.tag==='p'&&hn.className.indexOf('acl-ar-chat-line')>=0);check('human_display_name',hn.children.some(n=>n.textContent==='Other Human'));check('current_user_is_you',mn.children.some(n=>n.textContent==='You'));check('agent_is_participant_row',an.tag==='p'&&an.className.indexOf('card')<0);check('message_uses_text_nodes',hn.children[hn.children.length-1].textContent==='<b>safe</b>');check('system_notice_safe',sn.textContent==='<script>');check('lifecycle_not_transcript_noise',tr.node(evt(5,'agent_thinking',{type:'agent',id:9,name:'Bot'}))===null);check('stable_actor_color',tr.color(human.actor)===tr.color(human.actor));check('restrained_color_palette',Transcript.colors.length===8&&Transcript.colors.every(c=>/^#[0-9a-f]{6}$/i.test(c)));
tr.append([human,mine],false);let before=list.children.length;tr.append([mine,agent],false);check('poll_appends_only_new_rows',list.children.length===before+1);list.scrollTop=10;let oldTop=list.scrollTop;tr.prepend([system]);check('history_prepends_only_older_rows',list.children[0]===sn||list.children.length===4);check('history_scroll_anchor',list.scrollTop===oldTop+20);check('near_bottom_autoscroll_source',roomSource.indexOf('nearBottom(list)')>=0);check('history_reader_not_forced_source',roomSource.indexOf('if(!atBottom&&visible.length)')>=0);
const members=new Members(null,{currentUserId:1,currentUserName:'Me',agents:[{id:9,name:'Bot'}]},doc);check('member_seed_deduplicates',Object.keys(members.people).length===2);members.consume([human,human]);check('visible_actor_added_once',Object.keys(members.people).length===3);members.consume([evt(6,'agent_thinking',{type:'agent',id:9,name:'Bot'})]);check('lifecycle_updates_agent_state',members.people['agent:9'].state==='Thinking');const retryableFailure=Object.assign(evt(7,'agent_failed',{type:'agent',id:9,name:'Bot'}),{metadata:{retryable:true,error:'Temporary provider failure.'}});members.consume([retryableFailure]);check('retryable_failure_projects_queued',members.people['agent:9'].state==='Queued');const terminalFailure=Object.assign(evt(8,'agent_failed',{type:'agent',id:9,name:'Bot'}),{metadata:{retryable:false,error:'Terminal provider failure.'}});members.consume([terminalFailure]);check('terminal_failure_projects_error',members.people['agent:9'].state==='Error');const completed=evt(9,'agent_completed',{type:'agent',id:9,name:'Bot'});members.consume([completed]);check('completed_returns_ready',members.people['agent:9'].state==='Ready');members.applyAgentStates([{agent_id:9,state:'ready'}]);members.consume([retryableFailure,completed]);check('historical_retry_then_completion_remains_ready',members.people['agent:9'].state==='Ready');check('retryable_and_terminal_lifecycle_states_are_distinct',Members.lifecycleState(retryableFailure)==='Queued'&&Members.lifecycleState(terminalFailure)==='Error');check('member_selection_opens_inspector',appSource.indexOf('memberInfo')>=0&&appSource.indexOf('dialogs.open')>=0);check('inspector_escape_close',dialogSource.indexOf("event.key==='Escape'")>=0);check('inspector_focus_return',dialogSource.indexOf('trigger.focus()')>=0&&dialogSource.indexOf("querySelectorAll('[data-member-key]')")>=0);
const authoritativeReady=[{agent_id:9,state:'ready'}],historicalPause={id:10,room_id:7,type:'presence_change',actor:{type:'system',id:0,name:'Room system'},target:{type:'agent',id:9,name:'Bot'},metadata:{participation_state:'paused',auto_muted:false}};
members.applyAgentStates(authoritativeReady);members.consume([terminalFailure],{replay:true});check('initial_old_terminal_failure_preserves_authoritative_ready',members.people['agent:9'].state==='Ready');
members.consume([terminalFailure]);members.applyAgentStates(authoritativeReady);check('incremental_old_terminal_failure_yields_to_authoritative_ready',members.people['agent:9'].state==='Ready');
members.consume([terminalFailure,historicalPause],{replay:true});check('history_old_lifecycle_and_presence_preserve_live_ready',members.people['agent:9'].state==='Ready'&&members.people['agent:9'].participation.state==='active');
check('room_initial_and_history_use_replay_mode',roomSource.includes('processEvents(store.all(),true)')&&roomSource.includes('processEvents(events,true)')&&roomSource.includes('members.consume(events,{replay:!!isInitial})'));
check('room_reapplies_authoritative_states_after_incremental_events',roomSource.includes('latestAgentStates=state&&state.agent_states||[]')&&roomSource.includes('members.applyAgentStates(latestAgentStates);agentSummary();'));
check('history_completion_does_not_mutate_live_failure_banner',roomSource.includes("if(!isInitial&&e.type==='agent_completed'")&&roomSource.includes("if(!isInitial&&e.type==='brain_run'&&e.metadata&&e.metadata.status==='completed'"));
const form=new Node('form'),input=new Node('textarea'),counter=new Node('span'),composer=new Composer(form,input,counter,12000);input.value='Hi ';input.selectionStart=input.selectionEnd=3;composer.insert('☺');check('emoji_inserts_at_cursor',input.value==='Hi ☺'&&input.focused);check('rich_text_disabled_explained',(template.match(/disabled title=/g)||[]).length>=3&&template.indexOf('Rich text arrives')>=0);let sends=0;composer.onSend=()=>{sends++;};input.value='go';input.dispatch('keydown',{key:'Enter',shiftKey:false});check('enter_sends_single_line',sends===1);input.dispatch('keydown',{key:'Enter',shiftKey:true});check('shift_enter_does_not_send',sends===1);composer.setMultiline(true);input.dispatch('keydown',{key:'Enter',ctrlKey:true});check('ctrl_enter_sends_multiline',sends===2);let sendAt=roomSource.indexOf('api.send'),clearAt=roomSource.indexOf('composer.clear()',sendAt),catchAt=roomSource.indexOf('.catch(function(error)',sendAt);check('failed_send_retains_draft',sendAt>=0&&clearAt>sendAt&&catchAt>clearAt);check('successful_send_clears_draft',/api\.send[\s\S]*composer\.clear\(\)[\s\S]*sync\.immediate/.test(roomSource));check('event_catchup_no_transcript_replace',!/api\.send[\s\S]{0,500}transcript\.replace/.test(roomSource));
check('mobile_member_drawer',css.indexOf('acl-ar-room-app--members-open')>=0&&css.indexOf('translateX')>=0);check('focused_mode_toggle',appSource.indexOf("toggle('focused')")>=0&&css.indexOf('--focused')>=0);check('compact_mode_toggle',css.indexOf('--compact')>=0);check('large_text_toggle',css.indexOf('--large-text')>=0);check('high_contrast_toggle',css.indexOf('--high-contrast')>=0);
const storage={data:{},getItem(k){return this.data[k]||null;},setItem(k,v){this.data[k]=v;}},prefs=new Preferences(1,storage,null);prefs.set('compact',true);let prefs2=new Preferences(1,storage,null);check('preferences_persist',prefs2.value.compact===true);storage.data[prefs.key]='{bad';let corrupt=new Preferences(1,storage,null);check('corrupt_preferences_safe',corrupt.value.compact===false);check('sound_defaults_off',Preferences.defaults.sound===false);const snd=new Sound(prefs,{hidden:false},{});check('sound_requires_interaction',snd.play('message',null,false)===false);snd.enable();check('sound_enable_arms',snd.armed&&snd.isEnabled());check('initial_history_silent',snd.play('message',null,true)===false);check('own_message_silent',snd.play('message',{actor:{type:'user',id:1},currentUserId:1},false)===false);
check('offline_status_source',roomSource.indexOf("statusbar.set('offline'")>=0);check('hidden_paused_status',roomSource.indexOf("statusbar.set('paused'")>=0);check('recovery_connected_status',roomSource.indexOf("statusbar.set('connected'")>=0);check('foreground_work_covers_150_second_independent_retry_schedule',(maxWorkCycles-1)*maxRetryPollMs>independentRetryScheduleMs);check('retryable_failures_do_not_raise_room_error',roomSource.includes("e.type==='agent_failed'&&e.metadata&&!e.metadata.retryable")&&roomSource.includes("e.metadata.status==='failed'&&!e.metadata.retryable"));check('agent_completion_clears_owned_failure_banner',roomSource.includes("clearFailureState('agent-failure',agentFailureKey(e))"));check('brain_completion_clears_owned_failure_banner',roomSource.includes("clearFailureState('brain-failure',brainFailureKey(e))"));check('historical_failures_remain_silent',roomSource.includes("if(!isInitial&&e.type==='agent_failed'")&&roomSource.includes("if(!isInitial&&e.type==='brain_run'"));check('shortcuts_scoped_to_root',appSource.indexOf("this.root.addEventListener('keydown'")>=0);check('dialog_focus_trap',dialogSource.indexOf("event.key!=='Tab'")>=0);check('reduced_motion_css',css.indexOf('prefers-reduced-motion:reduce')>=0);check('wrong_room_store_preserved',roomSource.indexOf('new ACLARRoomStore(config.roomId)')>=0);check('poll_overlap_preserved',roomSource.indexOf('new ACLARRoomSync')>=0);check('phase4_transport_files_retained',fs.existsSync(path.join(rootDir,'assets/js/room/store.js'))&&fs.existsSync(path.join(rootDir,'assets/js/room/sync.js')));check('no_unsafe_innerhtml',roomSource.indexOf('innerHTML')<0&&fs.readFileSync(path.join(rootDir,'assets/js/room/transcript.js'),'utf8').indexOf('innerHTML')<0);check('mobile_no_overflow_contract',css.indexOf('@media(max-width:520px)')>=0&&css.indexOf('max-width:100%')>=0);
console.log('PASS phase5_ui assertions='+assertions);}
try{run();}catch(e){console.error('FAIL phase5_ui: '+e.message);process.exit(1);}
