<?php
/** @var array $room @var array $agents @var array $bootstrap */
if ( ! defined( 'ABSPATH' ) ) {
	exit; }
$room_id           = (int) $room['id'];
$active            = 'active' === (string) $room['status'];
$participant_count = count( $agents ) + 1;
/* translators: %s: Room title. */
$room_aria_label = sprintf( __( '%s chat room', 'acl-agent-rooms' ), (string) $room['title'] );
/* translators: %s: Room title. */
$window_title = sprintf( __( 'ACL Agent Rooms — %s', 'acl-agent-rooms' ), (string) $room['title'] );
/* translators: %d: Number of participants. */
$participant_label = sprintf( _n( '%d participant', '%d participants', $participant_count, 'acl-agent-rooms' ), $participant_count );
/* translators: %d: Number of agents. */
$agent_label = sprintf( _n( '%d agent', '%d agents', count( $agents ), 'acl-agent-rooms' ), count( $agents ) );
?>
<section class="acl-ar-room acl-ar-room-app" data-room-id="<?php echo esc_attr( (string) $room_id ); ?>" data-bootstrap="<?php echo esc_attr( (string) wp_json_encode( $bootstrap ) ); ?>" role="region" aria-label="<?php echo esc_attr( $room_aria_label ); ?>">
<a class="acl-ar-room-app__skip" href="#acl-ar-log-<?php echo esc_attr( (string) $room_id ); ?>"><?php esc_html_e( 'Skip to transcript', 'acl-agent-rooms' ); ?></a><a class="acl-ar-room-app__skip" href="#acl-ar-message-<?php echo esc_attr( (string) $room_id ); ?>"><?php esc_html_e( 'Skip to message box', 'acl-agent-rooms' ); ?></a>
<header class="acl-ar-room-app__titlebar"><span class="acl-ar-room-app__icon" aria-hidden="true"><i></i><i></i></span><strong class="acl-ar-room-app__window-title"><?php echo esc_html( $window_title ); ?></strong><span class="acl-ar-room-app__connection"><span class="acl-ar-room-app__connection-light"></span><span data-status-connection><?php esc_html_e( 'Connecting', 'acl-agent-rooms' ); ?></span></span><div class="acl-ar-room-app__window-controls" role="group" aria-label="<?php esc_attr_e( 'Room window controls', 'acl-agent-rooms' ); ?>"><button type="button" data-action="compact" aria-pressed="false" title="<?php esc_attr_e( 'Compact transcript', 'acl-agent-rooms' ); ?>"><span aria-hidden="true">_</span><span class="screen-reader-text"><?php esc_html_e( 'Toggle compact transcript', 'acl-agent-rooms' ); ?></span></button><button type="button" data-action="focused" aria-pressed="false" title="<?php esc_attr_e( 'Focused room mode', 'acl-agent-rooms' ); ?>"><span aria-hidden="true">□</span><span class="screen-reader-text"><?php esc_html_e( 'Toggle focused room mode', 'acl-agent-rooms' ); ?></span></button><button type="button" data-action="collapse" aria-expanded="true" title="<?php esc_attr_e( 'Collapse room', 'acl-agent-rooms' ); ?>"><span aria-hidden="true">×</span><span class="screen-reader-text"><?php esc_html_e( 'Collapse or expand room', 'acl-agent-rooms' ); ?></span></button></div></header>
<div class="acl-ar-room-app__body"><div class="acl-ar-room-app__topicbar"><div class="acl-ar-room-app__topic-copy"><strong><?php echo esc_html( (string) $room['title'] ); ?></strong><span title="<?php echo esc_attr( wp_strip_all_tags( (string) $room['description'] ) ); ?>"><?php echo esc_html( wp_strip_all_tags( (string) ( $room['description'] ?: $room['top_context'] ) ) ); ?></span></div><span class="acl-ar-room-app__room-kind"><?php echo esc_html( ucfirst( (string) $room['visibility'] ) ); ?></span><button type="button" class="acl-ar-bevel-button" data-action="room-info"><?php esc_html_e( 'Room Info', 'acl-agent-rooms' ); ?></button><button type="button" class="acl-ar-bevel-button acl-ar-room-app__members-toggle" data-action="members" aria-expanded="false"><?php esc_html_e( 'People', 'acl-agent-rooms' ); ?></button></div>
<div class="acl-ar-room-app__workspace"><main class="acl-ar-room-app__transcript-pane"><div class="acl-ar-room__history"><button type="button" class="acl-ar-room__history-button acl-ar-bevel-button" hidden><?php esc_html_e( 'Load earlier messages', 'acl-agent-rooms' ); ?></button></div><div id="acl-ar-log-<?php echo esc_attr( (string) $room_id ); ?>" class="acl-ar-room__messages acl-ar-room-app__transcript" role="log" aria-live="polite" aria-relevant="additions" tabindex="0" aria-label="<?php esc_attr_e( 'Room transcript', 'acl-agent-rooms' ); ?>"><p class="acl-ar-room__empty"><?php esc_html_e( 'Connecting to the room…', 'acl-agent-rooms' ); ?></p></div><button type="button" class="acl-ar-room-app__new-messages acl-ar-bevel-button" data-action="new-messages" hidden><?php esc_html_e( 'New messages', 'acl-agent-rooms' ); ?></button></main>
<aside class="acl-ar-room-app__members" aria-label="<?php esc_attr_e( 'Room participants', 'acl-agent-rooms' ); ?>" aria-hidden="false"><div class="acl-ar-room-app__panel-title"><strong><?php esc_html_e( 'People Here', 'acl-agent-rooms' ); ?></strong><button type="button" data-action="members-close" aria-label="<?php esc_attr_e( 'Close participant list', 'acl-agent-rooms' ); ?>">×</button></div><div class="acl-ar-room-app__member-groups" data-member-list></div></aside></div>
<div class="acl-ar-room-app__toolbar" role="toolbar" aria-label="<?php esc_attr_e( 'Message and room tools', 'acl-agent-rooms' ); ?>"><button type="button" disabled title="<?php esc_attr_e( 'Rich text arrives in a later phase', 'acl-agent-rooms' ); ?>"><b>B</b></button><button type="button" disabled title="<?php esc_attr_e( 'Rich text arrives in a later phase', 'acl-agent-rooms' ); ?>"><i>I</i></button><button type="button" disabled title="<?php esc_attr_e( 'Rich text arrives in a later phase', 'acl-agent-rooms' ); ?>"><?php esc_html_e( 'Font', 'acl-agent-rooms' ); ?></button><span class="acl-ar-room-app__tool-separator" aria-hidden="true"></span><button type="button" data-action="emoji" aria-expanded="false" title="<?php esc_attr_e( 'Emoji and symbols', 'acl-agent-rooms' ); ?>">☺</button><button type="button" data-action="insert-member" title="<?php esc_attr_e( 'Insert selected member name', 'acl-agent-rooms' ); ?>">@</button><button type="button" data-action="clear" title="<?php esc_attr_e( 'Clear message', 'acl-agent-rooms' ); ?>">⌫</button><button type="button" data-action="multiline" aria-pressed="false" title="<?php esc_attr_e( 'Toggle multiline mode', 'acl-agent-rooms' ); ?>">↵</button><span class="acl-ar-room-app__tool-separator" aria-hidden="true"></span><button type="button" data-action="roll-command" aria-haspopup="dialog" title="<?php esc_attr_e( 'Roll dice', 'acl-agent-rooms' ); ?>">Dice</button><button type="button" data-action="coin-command" title="<?php esc_attr_e( 'Flip coin', 'acl-agent-rooms' ); ?>">Coin</button><button type="button" data-action="whisper-command" aria-haspopup="listbox" title="<?php esc_attr_e( 'Private whisper', 'acl-agent-rooms' ); ?>">Whisper</button><span class="acl-ar-room-app__tool-spacer"></span><button type="button" data-action="sound" aria-pressed="false" title="<?php esc_attr_e( 'Toggle room sounds', 'acl-agent-rooms' ); ?>">♪</button><button type="button" data-action="contrast" aria-pressed="false" title="<?php esc_attr_e( 'Toggle high contrast', 'acl-agent-rooms' ); ?>">◐</button><button type="button" data-action="large-text" aria-pressed="false" title="<?php esc_attr_e( 'Toggle large text', 'acl-agent-rooms' ); ?>">A+</button></div>
<?php
if ( ! empty( $bootstrap['features']['roomFiles'] ) ) :
	?>
	<div class="acl-ar-room-app__files-control"><button type="button" class="acl-ar-bevel-button" data-action="files" aria-haspopup="dialog" aria-expanded="false"><?php esc_html_e( 'Files', 'acl-agent-rooms' ); ?></button><span><?php esc_html_e( 'Select project files for the next request', 'acl-agent-rooms' ); ?></span></div><?php endif; ?>
<div class="acl-ar-room-app__command-menu" data-command-menu role="listbox" aria-label="<?php esc_attr_e( 'Room commands', 'acl-agent-rooms' ); ?>" hidden></div><div class="acl-ar-room-app__dice-popover" data-dice-popover role="dialog" aria-label="<?php esc_attr_e( 'Roll dice', 'acl-agent-rooms' ); ?>" hidden><label><?php esc_html_e( 'Notation', 'acl-agent-rooms' ); ?> <input type="text" value="d20" maxlength="32" data-dice-notation></label><div>
<?php
foreach ( array( 'd20', 'd6', '2d6', 'd100' )as$preset ) :
	?>
	<button type="button" data-dice-preset="<?php echo esc_attr( $preset ); ?>"><?php echo esc_html( $preset ); ?></button><?php endforeach; ?></div><button type="button" data-action="dice-roll"><?php esc_html_e( 'Roll', 'acl-agent-rooms' ); ?></button><button type="button" data-action="dice-close"><?php esc_html_e( 'Cancel', 'acl-agent-rooms' ); ?></button></div><div class="acl-ar-room-app__whisper-picker" data-whisper-picker role="listbox" aria-label="<?php esc_attr_e( 'Whisper recipient', 'acl-agent-rooms' ); ?>" hidden></div>
<div class="acl-ar-room-app__command-banner" data-command-banner role="status" aria-label="<?php esc_attr_e( 'Private compose mode', 'acl-agent-rooms' ); ?>" hidden><strong data-command-banner-label></strong><button type="button" class="acl-ar-bevel-button" data-action="command-cancel"><?php esc_html_e( 'Cancel', 'acl-agent-rooms' ); ?></button></div>
<div class="acl-ar-room-app__interaction-banner" data-interaction-banner role="status" aria-label="<?php esc_attr_e( 'Message interaction', 'acl-agent-rooms' ); ?>" hidden><strong data-interaction-label></strong><button type="button" class="acl-ar-bevel-button" data-action="interaction-cancel"><?php esc_html_e( 'Cancel', 'acl-agent-rooms' ); ?></button></div><form class="acl-ar-room__composer acl-ar-room-app__composer"><label class="screen-reader-text" for="acl-ar-message-<?php echo esc_attr( (string) $room_id ); ?>"><?php esc_html_e( 'Message', 'acl-agent-rooms' ); ?></label><textarea id="acl-ar-message-<?php echo esc_attr( (string) $room_id ); ?>" rows="2" maxlength="12000" placeholder="<?php esc_attr_e( 'Type a message…', 'acl-agent-rooms' ); ?>" <?php disabled( ! $active ); ?>></textarea><div class="acl-ar-room-app__composer-side"><span class="acl-ar-room-app__count" data-character-count>0 / 12000</span><button type="submit" class="acl-ar-room-app__send acl-ar-bevel-button" <?php disabled( ! $active ); ?>><?php esc_html_e( 'Send', 'acl-agent-rooms' ); ?></button></div><div class="acl-ar-room__state" role="status" aria-live="polite" hidden></div></form>
<footer class="acl-ar-room-app__statusbar"><span><i class="acl-ar-room-app__status-light"></i><span data-status-state><?php esc_html_e( 'Connecting', 'acl-agent-rooms' ); ?></span></span><span data-status-room><?php echo esc_html( (string) $room['title'] ); ?></span><span data-status-members><?php echo esc_html( $participant_label ); ?></span><span data-status-agents><?php echo esc_html( $agent_label ); ?></span><span data-status-sound><?php esc_html_e( 'Sound off', 'acl-agent-rooms' ); ?></span><span data-status-unread hidden></span><span data-status-time><?php esc_html_e( 'Not synced', 'acl-agent-rooms' ); ?></span></footer></div>
<div class="acl-ar-room-app__reaction-picker" data-reaction-picker hidden role="dialog" aria-label="<?php esc_attr_e( 'Message reactions', 'acl-agent-rooms' ); ?>"></div><div class="acl-ar-room-app__picker" data-picker hidden role="dialog" aria-label="<?php esc_attr_e( 'Emoji and symbols', 'acl-agent-rooms' ); ?>"></div><div class="acl-ar-room-app__modal" data-modal hidden><div class="acl-ar-room-app__modal-backdrop" data-action="dialog-close"></div><section class="acl-ar-room-app__dialog" role="dialog" aria-modal="true" aria-labelledby="acl-ar-dialog-title-<?php echo esc_attr( (string) $room_id ); ?>" tabindex="-1"><header><strong id="acl-ar-dialog-title-<?php echo esc_attr( (string) $room_id ); ?>" data-dialog-title><?php esc_html_e( 'Room information', 'acl-agent-rooms' ); ?></strong><button type="button" data-action="dialog-close" aria-label="<?php esc_attr_e( 'Close dialog', 'acl-agent-rooms' ); ?>">×</button></header><div class="acl-ar-room-app__dialog-content" data-dialog-content></div><footer><button type="button" class="acl-ar-bevel-button" data-action="dialog-close"><?php esc_html_e( 'Close', 'acl-agent-rooms' ); ?></button></footer></section></div>
</section>
